### ISSUE TITLE
translation file with UI module

### ISSUE THREAD

**Issue by tomalaforge** [NetanelBasal/transloco-with-nx-libs#19]
Hello,

Very nice example, but how do you do if you have a Shared module with its own translation used by lib A and lib B. 
In your documentation, you say that you provide the TRANSLOCO_SCOPE inside the component, but that's not working and you loose translation from your lib A or B. 

The only solution is to put the translation inside your apps translation files, but that makes the shared lib very tied. 

Any help are welcome

**Comment by tomalaforge** [comment]
I've update the project to v12 and created an example about what I said in the previous comment area, but I'm not allowed to push my branch on your server. How can I do this to create a pull request?

**Comment by NetanelBasal** [comment]
https://www.dataschool.io/how-to-contribute-on-github/
